/// Flutter icons NavigationBarIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavigationBarIcons
///      fonts:
///       - asset: fonts/NavigationBarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NavigationBarIcons {
  NavigationBarIcons._();

  static const _kFontFam = 'NavigationBarIcons';
  static const String? _kFontPkg = null;

  static const IconData tech = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notif = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData khane = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class Search {
  Search._();

  static const _kFontFam = 'Search';
  static const String? _kFontPkg = null;

  static const IconData search = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}